#!/usr/bin/env bash
# Concatenates upstream Things theme.css with Starscape overrides.
# Run after pulling upstream updates: cp ../../../_others/obsidian-things/theme.css upstream/theme.css && ./build.sh
set -euo pipefail
cd "$(dirname "$0")"

{
  echo "/* Starscape Things — generated by build.sh. Do not edit directly. */"
  echo "/* Upstream: https://github.com/colineckert/obsidian-things (MIT, @colineckert) */"
  echo
  cat upstream/theme.css
  echo
  echo "/* ===== Starscape overrides ===== */"
  cat starscape-overrides.css
} > theme.css

echo "Wrote theme.css ($(wc -l < theme.css) lines)"
